// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../lib/types';

// Validation des variables d'environnement
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error(
    '❌ Variables d\'environnement Supabase manquantes.\n' +
    'Vérifiez VITE_SUPABASE_URL et VITE_SUPABASE_ANON_KEY dans votre .env'
  );
}

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Composant de debug optionnel
export const SupabaseDebugger = () => {
  if (import.meta.env.DEV) {
    console.group('🔍 Configuration Supabase');
    console.log('URL:', supabaseUrl);
    console.log('Mode:', import.meta.env.MODE);
    console.groupEnd();
  }
  return null;
};