// This file is automatically generated. Do not edit it directly.
import { useEffect } from 'react';
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../lib/types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY

// Créez un composant temporaire pour afficher les variables
const EnvDebugger = () => {
  useEffect(() => {
    console.log('🔍 Variables d\'environnement Lovable:');
    console.log('VITE_SUPABASE_URL:', import.meta.env.VITE_SUPABASE_URL);
    console.log('VITE_SUPABASE_ANON_KEY:', import.meta.env.VITE_SUPABASE_ANON_KEY);
    console.log('NODE_ENV:', import.meta.env.MODE);
  }, []);

  return null;
};

// Utilisez-le temporairement dans votre app
// <EnvDebugger />
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});