// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { SUPABASE_CONFIG } from '@/lib/supabase-config';

if (!SUPABASE_CONFIG.url || !SUPABASE_CONFIG.key) {
  throw new Error('Variables Supabase manquantes dans .env');
}

export const supabase = createClient(
  SUPABASE_CONFIG.url,
  SUPABASE_CONFIG.key,
  SUPABASE_CONFIG.options
);

// Test de connexion amélioré
const testConnection = async () => {
  try {
    // Test authentification
    const { data: authData, error: authError } = await supabase.auth.getSession();
    if (authError) {
      throw new Error(`Erreur auth: ${authError.message}`);
    }

    // Test accès base de données
    const { data: dbData, error: dbError } = await supabase
      .from('profiles')
      .select('count');

    if (dbError) {
      throw new Error(`Erreur DB: ${dbError.message}`);
    }

    console.log('✅ Connexion Supabase OK:', {
      auth: 'connecté',
      db: 'accessible',
      hasSession: !!authData.session
    });

  } catch (err) {
    console.error('❌ Erreur connexion:', err.message);
  }
};

// // Exécuter le test au démarrage
// testConnection();