import React from 'react';
import {
  Shield,
  User,
  Building,
  Globe,
  CreditCard,
  MessageSquare,
  Wrench,
  Check,
  AlertTriangle,
  Info,
  Lock,
  Loader2 as Spinner,
  Crown,
  Settings,
  Phone,
  Mail,
  MapPin,
  Calendar,
  Clock,
  Star,
  Plus,
  Minus,
  Edit,
  Trash,
  Search,
  Filter,
  Download,
  Upload,
  Eye,
  EyeOff,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowRight,
  ArrowLeft,
  Home,
  BarChart3,
  Users,
  Car,
  Wrench as Tool,
  FileText,
  Database,
  Server,
  Zap,
  Target,
  TrendingUp,
  TrendingDown,
  DollarSign,
  Euro,
  Percent,
  Hash,
  AtSign,
  PhoneCall,
  Video,
  Camera,
  Mic,
  Headphones,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Printer,
  HardDrive,
  Cpu,
  Power,
  Battery,
  Wifi,
  Bluetooth,
  Signal,
  Volume,
  VolumeX,
  Volume1,
  Volume2,
  Play,
  Pause,
  Square,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Shuffle,
  Repeat,
  Repeat1,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Meh,
  Flame,
  Snowflake,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Wind,
  Umbrella,
  Droplets,
  Waves,
  Mountain,
  Leaf,
  Flower2 as Flower,
  Sprout,
  Bug,
  Bird,
  Cat,
  Dog
} from 'lucide-react';

export const Icons = {
  // Icônes principales du workflow
  shield: Shield,
  user: User,
  building: Building,
  globe: Globe,
  creditCard: CreditCard,
  messageSquare: MessageSquare,
  wrench: Wrench,
  check: Check,
  alertTriangle: AlertTriangle,
  info: Info,
  lock: Lock,
  spinner: Spinner,
  crown: Crown,
  settings: Settings,

  // Icônes de contact
  phone: Phone,
  mail: Mail,
  mapPin: MapPin,

  // Icônes de temps
  calendar: Calendar,
  clock: Clock,

  // Icônes d'évaluation
  star: Star,

  // Icônes d'action
  plus: Plus,
  minus: Minus,
  edit: Edit,
  trash: Trash,
  search: Search,
  filter: Filter,
  download: Download,
  upload: Upload,

  // Icônes de visibilité
  eye: Eye,
  eyeOff: EyeOff,

  // Icônes de navigation
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,

  // Icônes de navigation principale
  home: Home,
  barChart3: BarChart3,
  users: Users,

  // Icônes automobiles
  car: Car,
  tool: Tool,

  // Icônes de documents
  fileText: FileText,

  // Icônes techniques
  database: Database,
  server: Server,
  zap: Zap,
  target: Target,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,

  // Icônes financières
  dollarSign: DollarSign,
  euro: Euro,
  percent: Percent,

  // Icônes de communication
  hash: Hash,
  atSign: AtSign,
  phoneCall: PhoneCall,

  // Icônes multimédia
  video: Video,
  camera: Camera,
  mic: Mic,
  headphones: Headphones,

  // Icônes d'appareils
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  printer: Printer,
  hardDrive: HardDrive,
  cpu: Cpu,
  power: Power,
  battery: Battery,

  // Icônes de connectivité
  wifi: Wifi,
  bluetooth: Bluetooth,
  signal: Signal,

  // Icônes audio
  volume: Volume,
  volumeX: VolumeX,
  volume1: Volume1,
  volume2: Volume2,

  // Icônes de lecture
  play: Play,
  pause: Pause,
  square: Square,
  skipBack: SkipBack,
  skipForward: SkipForward,
  rewind: Rewind,
  fastForward: FastForward,
  shuffle: Shuffle,
  repeat: Repeat,
  repeat1: Repeat1,

  // Icônes d'émotions
  heart: Heart,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  smile: Smile,
  frown: Frown,
  meh: Meh,

  // Icônes naturelles
  flame: Flame,
  snowflake: Snowflake,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  cloudRain: CloudRain,
  cloudSnow: CloudSnow,
  cloudLightning: CloudLightning,
  wind: Wind,
  umbrella: Umbrella,
  droplets: Droplets,
  waves: Waves,
  mountain: Mountain,
  leaf: Leaf,
  flower: Flower,
  sprout: Sprout,

  // Icônes d'animaux
  bug: Bug,
  bird: Bird,
  cat: Cat,
  dog: Dog
};

